### ISSUE TITLE
still an issue with drifter data with uncorrected fill values

### ISSUE THREAD

**Issue by selipot** [argovis/demo_notebooks#1]
The notebook works fine as it is (in binder) but fails when changing the `ifloat` number (to 0 as an example) in the plot/example showing the Argo float temperature profile and the drifter. I believe that is the issue that Phillipe identified with the drifter data that contains non conventional fill values that are not converted to NaN.

**Comment by BillMills** [comment]
Hi @selipot, thanks for your attention on this! Commit f74c40b2de25832e01100e27906211b800222152 addresses this issue - I think the problem was not the fill values but rather that the gross regional search turns up some floats that don't have drifters sufficiently close by to get picked up in the subsequent proximity search.

The fill values issue was corrected last week and merged in as a pipeline correction in https://github.com/argovis/drifter-sync/pull/4. Thanks to you and @philippemiron for your guidance there.
